### ISSUE TITLE
Set/Get values in selectable format - Value, String or Position

### ISSUE THREAD

**Issue by zdenekstepanek** [dudest/node-red-contrib-qsys#5]
QSC offer to Get and Set control values in three formats: Text, Value and Position. For faders it is like that - from QRC manual:

{
  "jsonrpc": "2.0", 
  "result": {
    "Name": "My APM",
    "Controls": [
    {
      "Name": "ent.xfade.gain", 
      "Value": ‐70.0,
      "String": "‐70.0dB" 
      "Position": 0.25
    }
    ]
  }
}

Position is number from 0 to 1 and it is like a position of knob, so it is unconnected to Min and Max value of fader in QSC Designer. It is very useful to control some faders in this way, for example if want to enable user control from -20dB to 0dB, then you may set fader in QSC Designer to this values, but in Node-Red you have value 0-1, so 0% to 100%. If you want to change gain range, you only have to change Min/Max values in QSC Designer.

**Describe the solution you'd like**
On qsys-ControlSet node new selectable combo box with options: Value, String, Position.

Or three input/output points with three variants. It may be useful to read more variants in one step and with one node.

**Describe alternatives you've considered**
Convert ValueMin-ValueMax scale to number 0.000-1.000, work with that number, and after convert back to ValueMin-ValueMax scale. Im using number "zero to one" together with rotary encoder in ESPHome, where I have 0 to 100%. Yes, it is possible to work with dB´s in whole Node-Red and ESPHome, but it is about rework whole system.

At this moment Im using telnet connection to Core and parsing of text responses like this: "cv "Analog_Volume_Value" "-70.0dB" -70 0.25"

**Comment by dudest** [comment]
Feature request noted.

**Comment by zdenekstepanek** [comment]
Hi,

I want to say that this is also a BUG. Responses in "Value" and "Position" formats works for faders and other numerical things. But this doesnt work for text-only responses. I got "0" every time from qsys-ControlSet node.

See my example, what i got from telnet:

cv "PresetSelectorValue" "70mm Baby-Boom" 0 0

**Comment by dudest** [comment]
For it to be a bug it would need to be implemented. I don't set or get position or string, only value. be patient and I'll eventually implement this when I get a chance. Otherwise if you cannot wait, you can use the `tcp request` and `function` nodes, they work great too.

**Comment by dudest** [comment]
@zdenekstepanek 

v1.0.3 published. see readme for changes.

**Comment by zdenekstepanek** [comment]
It works like a charm. Thank you very much.
