### ISSUE TITLE
Q-SYS 9.10.1 causing Node-RED to crash

### ISSUE THREAD

**Issue by VALMOR-NZ** [dudest/node-red-contrib-qsys#8]
I've been running 1.0.2 with Q-SYS version 9.9 and things were fine, after bringing Q-SYS up to version 9.10.1 I started experiencing Node-RED crashing with the following error in the console:

```
2 May 01:10:57 - [red] Uncaught Exception:
2 May 01:10:57 - [error] SyntaxError: Unexpected token i in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/data/node_modules/node-red-contrib-qsys/lib/qsys-core.js:98:36)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

I'm running Node-RED in a container on a Mikrotik router so this could certainly be a niche case.
I upgraded from 1.0.2 to 1.0.3 but still experience the same issue.

I am rolling the Q-SYS back to 9.9 to confirm.

**Comment by dudest** [comment]
Hi @VALMOR-NZ,

Did the problem persist on 9.9?

I still use 9.4 LTS unless there is a feature required only available on a later version.

**Comment by VALMOR-NZ** [comment]
Hey @dudest,

Yeah I was onsite for a few hours after rolling back to 9.9 and it remained stable.

In the release notes for 9.10 I believe there's reference to a change to QRC, but does not go into detail. 

Yeah that's really a good policy to maintain, I have had to roll another system back from 9.10.1 after TSCs would power cycle after loading the UCI, chased it for a while expecting it to be a network issue since there were also numerous changes there too.

**Comment by dudest** [comment]
@VALMOR-NZ, Finally merged your pull request. Thanks for your contribution! 👍
